### PR TITLE
Add checkbox page

### PR DESCRIPTION
**Pull request by fmhoeger**
Here is another PR for generating pages with checkboxes as options, including the possiblity to force the user to tick at least one checkbox (`force_answer`). The `javascript` argument allows for passing in javascript code to control the checkboxes' behaviour (e.g., clicking a "None" checkbox to untick other previously ticked checkboxes).

In addition, I made some minor changes in the documentation for radiobutton_NAFC_page and in the precondition for the make_ui_radiobutton_NAFC function plus a correction in the corresponding test. Should I better reverse those changes to not mix them with the checkbox page feature?

### CODE REVIEW

**Comment by pmcharrison** [comment]
Hi @fmhoeger , thanks for this! Don't worry about the mixed commits, that's fine.

The new checkbox page looks great. However, I'm not sure about the `get_answer` function, which just pastes together the selected items, producing something like this:

``` r
$results
$results$Hello
[1] "Choice B,Choice C"
```

Obviously, this is not so good if the choices already have commas in them, it makes things difficult to parse.

I would prefer it if `get_answer` just returned a character vector of the selected items. I understand that it is easier to construct a CSV file of the final results if you use your method. However, to me this is less important than maintaining natural data structures for the native parts of the software.

**Comment by fmhoeger** [comment]
Hi @pmcharrison , of course it is much better to retain the checkbox results as a character vector. I have changed the code accordingly, incl. some improvements to the docs and manual test.

**Comment by pmcharrison** [comment]
Cool! In that case, I think you should also update the behaviour when no checkboxes are checked, presumably it would be most consistent if it returned an empty character vector, rather than the current behaviour, which is to return `""`?

**Comment by fmhoeger** [comment]
Absolutely! Fixed it.

**Comment by pmcharrison** [comment]
Thanks very much! If it's OK, I'm going to snooze this until 14 September, when I plan to do the next bit of psychTestR development. We can roll this into the other changes we've been discussing.

**Comment by fmhoeger** [comment]
Great, that's fine!

**Pull request merged**
