### PR TITLE
Render problems_info as HTML

### PR DESCRIPTION
**Pull request by fmhoeger**
Rendering `problems_info` as HTML instead of text would allow for an internationalised footer containing email adresses/links and other HTML formatting tags.

### CODE REVIEW

**Comment by pmcharrison** [comment]
Good idea but this doesn't quite work yet because `test_options` still enforces that `problems_info` be a string. This check needs to be updated.

**Comment by fmhoeger** [comment]
The `problems_info` argument of `test_options` is still a string (that can possibly contain HTML code).
E-Mail adresses are automatically rendered as mailto links. Renders correctly:
footer_internationalized
String is `"Probleme?<br>Dann schreibe eine E-Mail an musicsophistication@gmail.com mit dem Verweis auf diese Seite."`

**Comment by pmcharrison** [comment]
Ah, I see! I expected that HTML code would be specified using HTML tags objects, e.g. tags$strong(). The problem with your way is that the user has to manually escape special characters, unless I'm misunderstanding. This is inconsistent with the rest of psychTestR, which automatically escapes text (e.g. in the prompt argument) unless informed otherwise by being passed HTML objects.

**Comment by pmcharrison** [comment]
So, just to be clear, I think the interface should work like this:

``` r
test_options(problems_info = tags$span(
    "Problem?", 
    tags$br(), 
    "Dann schreibe eine E-Mail an musicsophistication@gmail.com mit dem Verweis auf diese Seite."
))
```

**Comment by pmcharrison** [comment]
To get this working, I think you just need to do the following: 

* If the input to `uiOutput` is a string, automatically wrap it in `tags$span` (this gets the escaping to work).
* Update the input type check in `test_options`.

**Comment by fmhoeger** [comment]
Thank you for the clarifications and hints!
This small change turned out to entail a whole slew of checks to make it work.

**Comment by pmcharrison** [comment]
Hi @fmhoeger, sorry, still not quite there yet. It is important that you should be able to provide different problems_infos for different languages. Previously this was achieved by providing a named character vector. But your new shiny.tag implementation doesn't implement this internationalisation. I think the analogous interface, extended to allow the HTML features you want, should be a named list of shiny.tags, with one element for each language.

A further implementation hint - you allow different input types to test_options, and these different object types propagate to  server.R, forcing you to write conditional logic there. A nicer strategy might be to homogenise the object types within the test_options function, so that problems_info ends up being represented as HTML even if the user only originally provided it in a string.

I'm sorry for the complications here. I'm aware your original solution was very quick to code, and things have become more complicated....

**Comment by fmhoeger** [comment]
Hi @pmcharrison, 
no need to be sorry here! Regarding the first part of your comment - it is possible to provide different problems_infos for different languages since problems_info can be translated using the `translate` function of `i18n_dict` before passing it to `psychTestR::make_test` using the standard dictionary. E.g., one can use following helper function, the return value of which is passed to `make_test`
```
problems_info <- function(researcher_email, dict, language) {
  shiny::tags$span(
    dict$translate("PROBLEMS_INFO_1", language),
    shiny::tags$a(href = paste0("mailto:", researcher_email), researcher_email),
    dict$translate("PROBLEMS_INFO_2", language))
}
```
Of course this would make `i18n_problems_info` obsolete, wouldn't it? What was your reasoning behind doing the translation in server.py and not just using i18n_dict$translate like in the above? I am sure there must be some specific reason and I just want to be clear on this before going any further.

**Comment by pmcharrison** [comment]
Hi @fmhoeger , thanks for the follow up!

The reason that one wants to perform the translation in server.py, rather than before make_test as in your example, is to support situations where you want to host a single Shiny app online that supports multiple languages, that can be selected simply by the URL. I think your solution would force the app to commit to a single language.

**Comment by fmhoeger** [comment]
It always was a mistery to me, why the languages argument was assigned the vector of all possible languages when the first language was selected by default anyway. But, of course, you also want to be able to switch languages once the shiny app is deployed on a server. In hindsight this sounds all too obvious.

The changes I made to the code now allow the named character vector to be translated at runtime again. I didn't follow your suggestion of homogenising the object types already within `test_options` as this turned out to require additional logic for inspecting problems_info inside `i18n_problems_info` later. Nonetheless, the code looks simpler and I hope it's going in the right direction now.

**Comment by pmcharrison** [comment]
Great! I think the code of your solution is working good now. Last thing, I would just propose updating the documentation slightly, to something like this:

```
#' The default value, "default", gives
#' a standard English message including the researcher's email (if provided).
#' Alternatively, the argument can be either
#' a) an unnamed character scalar providing a non-internationalised message,
#' b) a named character vector of internationalised messages with the names
#' corresponding to language codes,
#' c) a named list of HTML tag objects, for example
#' \code{list(EN = htmltools::tagList("Normal text", htmltools::tags$em("italics")))}.
```

**Comment by fmhoeger** [comment]
Ok, I have updated the documentation.

**Comment by pmcharrison** [comment]
Thanks, the Rd file still needs rebuilding though. I probably don't I have the permissions to do that on your branch, maybe you could do it?

**Comment by fmhoeger** [comment]
Yep, done!

**Comment by pmcharrison** [comment]
Thanks! merged

**Pull request merged**
