### PR TITLE
Addition of additional scripts argument to test_options and gamifyr features

### PR DESCRIPTION
**Pull request by sebsilas**
+ revisions requested in #103

### CODE REVIEW

**Comment by sebsilas** [comment]
> I'm confused, why did you close the old pull request and start a new one?

Sorry, just tried to separate it out. I'll update in the same pull request from now on.

**Comment by pmcharrison** [comment]
Can we return to the old one, so that I can my old comment thrads?

**Comment by sebsilas** [comment]
> Can we return to the old one, so that I can my old comment threads?

Sure, sorry about that. I don't seem to have permission to do that, so you'll need to reopen it. Closing this now then.

**Comment by pmcharrison** [comment]
No problem!

**Pull request closed without merging**
